import { expect, test } from "@playwright/test"
import { calculate, fillMoney, login, newDossier, next, personal } from "./helpers"

test("doorstromer: verkopen en kopen met meeneemregeling", async ({ page }) => {
  await login(page, "doorstromer")
  await newDossier(page, /Verhuizen: kopen én verkopen/)
  await personal(page, ["1984-03-01", "1986-07-01"])
  await page.getByLabel("Ik heb eerder een eigen woning gehad").first().check()
  await next(page, "inkomen")
  await fillMoney(page, "Bruto jaarsalaris (zonder vakantiegeld)", "70000", 0)
  await fillMoney(page, "Bruto jaarsalaris (zonder vakantiegeld)", "42000", 1)
  await next(page, "verplichtingen")
  await next(page, "vermogen")
  await fillMoney(page, "Spaargeld", "50000")
  await next(page, "huidige-woning")
  await fillMoney(page, "WOZ-waarde", "400000")
  await fillMoney(page, "Geschatte marktwaarde", "440000")
  await fillMoney(page, "Verwachte verkoopprijs", "440000")
  await page.getByRole("button", { name: "Leningdeel toevoegen" }).click()
  await fillMoney(page, "Restschuld", "230000")
  await page.getByLabel("Rente", { exact: true }).fill("2.4")
  await page.getByLabel("Einde rentevaste periode").fill("2030-01-01")
  await page.getByLabel("Einddatum looptijd").fill("2046-01-01")
  await page.getByLabel("Meenemen naar de nieuwe woning (meeneemregeling)").check()
  await page.getByLabel("Eerst kopen of eerst verkopen?").selectOption("buy_first")
  await next(page, "nieuwe-woning")
  await fillMoney(page, "Koopsom", "560000")
  await next(page, "voorkeuren")
  await next(page, "risicos")
  await next(page, "overzicht")
  await calculate(page)
  await expect(page.getByText("Huidige woning", { exact: true })).toBeVisible()
  await expect(page.getByText("Eigenwoningreserve").first()).toBeVisible()
  await expect(page.getByText("Overbruggingskrediet").first()).toBeVisible()
  await expect(page.getByText(/Bestaand deel/).first()).toBeVisible()
  expect(await page.getByTestId("lender-row").count()).toBeGreaterThanOrEqual(15)
})
